name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    uses: ./.github/workflows/packer-build.yml
    with:
      release: true
      version: ${{ github.ref_name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}